//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineAppointmentUI.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VaccineAppointmentUI.Resources.Translations.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        public static string AddressHeader {
            get {
                return ResourceManager.GetString("AddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อายุ.
        /// </summary>
        public static string AgeHeader {
            get {
                return ResourceManager.GetString("AgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่นัดครั้งถัดไป.
        /// </summary>
        public static string AppointDateHeader {
            get {
                return ResourceManager.GetString("AppointDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แอพพลิเคชันกรองข้อมูลนัดวัคซีน COVID-19.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเกิด.
        /// </summary>
        public static string BirthdateHeader {
            get {
                return ResourceManager.GetString("BirthdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขประจำตัวประชาชน.
        /// </summary>
        public static string CidHeader {
            get {
                return ResourceManager.GetString("CidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรองข้อมูลจากผู้ฉีด.
        /// </summary>
        public static string DocCodeLabel {
            get {
                return ResourceManager.GetString("DocCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเพื่อกรองข้อมูลเฉพาะผู้ฉีดท่านนี้.
        /// </summary>
        public static string DocCodeTooltip {
            get {
                return ResourceManager.GetString("DocCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นัดจากเข็มที่.
        /// </summary>
        public static string DoseLabel {
            get {
                return ResourceManager.GetString("DoseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่นัดครั้งถัดไป.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกวันนัดเข็มถัดไป (ปี เป็น ค.ศ. เท่านั้น).
        /// </summary>
        public static string EndDateTooltip {
            get {
                return ResourceManager.GetString("EndDateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งออก Excel (.xlsx).
        /// </summary>
        public static string ExportExcelBtnText {
            get {
                return ResourceManager.GetString("ExportExcelBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หากข้อมูลถูกจัดเตรียมเรียบร้อย Excel จะเปิดขึ้นมาโดยอัตโนมัติ.
        /// </summary>
        public static string ExportExcelMessage {
            get {
                return ResourceManager.GetString("ExportExcelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาข้อมูล.
        /// </summary>
        public static string FetchBtnText {
            get {
                return ResourceManager.GetString("FetchBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นข้อมูลเสร็จสิ้น.
        /// </summary>
        public static string FetchedMessage {
            get {
                return ResourceManager.GetString("FetchedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ-สกุล.
        /// </summary>
        public static string FullNameHeader {
            get {
                return ResourceManager.GetString("FullNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN.
        /// </summary>
        public static string HnHeader {
            get {
                return ResourceManager.GetString("HnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ฉีด.
        /// </summary>
        public static string InjectionDateHeader {
            get {
                return ResourceManager.GetString("InjectionDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พร้อมใช้งาน.
        /// </summary>
        public static string ReadyMessage {
            get {
                return ResourceManager.GetString("ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่มารับบริการ.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกวันที่ให้บริการ (ปี เป็น ค.ศ. เท่านั้น).
        /// </summary>
        public static string StartDateTooltip {
            get {
                return ResourceManager.GetString("StartDateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรองข้อมูลจากแผน.
        /// </summary>
        public static string SubVacLabel {
            get {
                return ResourceManager.GetString("SubVacLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเพื่อกรองข้อมูลข้อมูลเฉพาะแผนนัดดังกล่าว.
        /// </summary>
        public static string SubVacTooltip {
            get {
                return ResourceManager.GetString("SubVacTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        public static string TelHeader {
            get {
                return ResourceManager.GetString("TelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัคซีน.
        /// </summary>
        public static string VaccineLabel {
            get {
                return ResourceManager.GetString("VaccineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกประเภทวัคซีนที่ต้องการกรองข้อมูล.
        /// </summary>
        public static string VaccineTooltip {
            get {
                return ResourceManager.GetString("VaccineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัคซีน.
        /// </summary>
        public static string VacNameHeader {
            get {
                return ResourceManager.GetString("VacNameHeader", resourceCulture);
            }
        }
    }
}
