<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>VaccineAppointmentUI</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Authors>Narawit Khammanart</Authors>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\valid.png" />
    <None Remove="Resources\Fonts\Kanit-Bold.ttf" />
    <None Remove="Resources\Fonts\Kanit-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\valid.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\warning.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Fonts\Kanit-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Fonts\Kanit-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VaccineReportBackend\VaccineReportBackend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Translations\Resource.Designer.cs">
      <DependentUpon>Resource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Translations\Resource.th-TH.Designer.cs">
      <DependentUpon>Resource.th-TH.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Translations\Resource.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Translations\Resource.th-TH.resx">
      <LastGenOutput>Resource.th-TH.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
